name = "cocktail-battle"
main = "src/index.js"
compatibility_date = "2026-01-01"

[[rules]]
type = "Text"
globs = ["**/*.css"]
fallthrough = true

[[durable_objects.bindings]]
name = "PARTY_ROOM"
class_name = "PartyRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["PartyRoom"]
